"""remove_has_sale

Revision ID: 18acb19586d4
Revises: f9d47580f1dd
Create Date: 2026-08-16 15:06:39.157597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18acb19586d4'
down_revision: Union[str, Sequence[str], None] = 'f9d47580f1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_sale')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_sale', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
