"""add_surname

Revision ID: e4e77b7fd08c
Revises: 18acb19586d4
Create Date: 2026-08-16 15:08:06.177025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e77b7fd08c'
down_revision: Union[str, Sequence[str], None] = '18acb19586d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('has_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_sale')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
