server {
        listen       80;

        location /static/ {
            alias /usr/share/nginx/html/static/;
            autoindex off;
        }

        location / {
            proxy_pass http://127.0.0.1:8000;   # адрес, где работает Gunicorn
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
